// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v6.33.1
// source: api/proto/podfreeze.proto

package podfreeze

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	TargetIp      string                 `protobuf:"bytes,2,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeRequest) Reset() {
	*x = WakeRequest{}
	mi := &file_api_proto_podfreeze_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeRequest) ProtoMessage() {}

func (x *WakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_podfreeze_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeRequest.ProtoReflect.Descriptor instead.
func (*WakeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_podfreeze_proto_rawDescGZIP(), []int{0}
}

func (x *WakeRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *WakeRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

type WakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ReadyTimeMs   int32                  `protobuf:"varint,3,opt,name=ready_time_ms,json=readyTimeMs,proto3" json:"ready_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WakeResponse) Reset() {
	*x = WakeResponse{}
	mi := &file_api_proto_podfreeze_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WakeResponse) ProtoMessage() {}

func (x *WakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_podfreeze_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WakeResponse.ProtoReflect.Descriptor instead.
func (*WakeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_podfreeze_proto_rawDescGZIP(), []int{1}
}

func (x *WakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WakeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WakeResponse) GetReadyTimeMs() int32 {
	if x != nil {
		return x.ReadyTimeMs
	}
	return 0
}

var File_api_proto_podfreeze_proto protoreflect.FileDescriptor

var file_api_proto_podfreeze_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x64, 0x66,
	0x72, 0x65, 0x65, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x6f, 0x64,
	0x66, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x22, 0x4d, 0x0a, 0x0b, 0x57, 0x61, 0x6b, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x49, 0x70, 0x22, 0x66, 0x0a, 0x0c, 0x57, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x65, 0x61,
	0x64, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x72, 0x65, 0x61, 0x64, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x32, 0x50, 0x0a,
	0x0c, 0x4f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x40, 0x0a,
	0x0d, 0x57, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x16,
	0x2e, 0x70, 0x6f, 0x64, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x2e, 0x57, 0x61, 0x6b, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x6f, 0x64, 0x66, 0x72, 0x65, 0x65,
	0x7a, 0x65, 0x2e, 0x57, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f,
	0x64, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x64, 0x66, 0x72, 0x65, 0x65, 0x7a, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_podfreeze_proto_rawDescOnce sync.Once
	file_api_proto_podfreeze_proto_rawDescData = file_api_proto_podfreeze_proto_rawDesc
)

func file_api_proto_podfreeze_proto_rawDescGZIP() []byte {
	file_api_proto_podfreeze_proto_rawDescOnce.Do(func() {
		file_api_proto_podfreeze_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_podfreeze_proto_rawDescData)
	})
	return file_api_proto_podfreeze_proto_rawDescData
}

var file_api_proto_podfreeze_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_podfreeze_proto_goTypes = []any{
	(*WakeRequest)(nil),  // 0: podfreeze.WakeRequest
	(*WakeResponse)(nil), // 1: podfreeze.WakeResponse
}
var file_api_proto_podfreeze_proto_depIdxs = []int32{
	0, // 0: podfreeze.Orchestrator.WakeContainer:input_type -> podfreeze.WakeRequest
	1, // 1: podfreeze.Orchestrator.WakeContainer:output_type -> podfreeze.WakeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_podfreeze_proto_init() }
func file_api_proto_podfreeze_proto_init() {
	if File_api_proto_podfreeze_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_podfreeze_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_podfreeze_proto_goTypes,
		DependencyIndexes: file_api_proto_podfreeze_proto_depIdxs,
		MessageInfos:      file_api_proto_podfreeze_proto_msgTypes,
	}.Build()
	File_api_proto_podfreeze_proto = out.File
	file_api_proto_podfreeze_proto_rawDesc = nil
	file_api_proto_podfreeze_proto_goTypes = nil
	file_api_proto_podfreeze_proto_depIdxs = nil
}
